/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package application.customer.catalog;

/**
 *
 * @author shahi
 */
public class BannerShow extends javax.swing.JPanel {

    /**
     * Creates new form BannerShow
     */
    public BannerShow(String header, String btnTxt) {
        initComponents();
        
        headerBanner.setText(header);
        shopButton.setText(btnTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureHolder1 = new application.customer.design.PictureHolder();
        headerBanner = new javax.swing.JLabel();
        shopButton = new javax.swing.JButton();

        pictureHolder1.setBackground(new java.awt.Color(255, 92, 0));
        pictureHolder1.setOpaque(true);

        headerBanner.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        headerBanner.setForeground(new java.awt.Color(255, 255, 255));
        headerBanner.setText("Let's go shopping! Enjoy the momenutm of life with Echo Mart, hunting out the world treasures!");
        pictureHolder1.add(headerBanner);
        headerBanner.setBounds(40, 30, 850, 22);

        shopButton.setText("Shop Now!");
        pictureHolder1.add(shopButton);
        shopButton.setBounds(40, 110, 110, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureHolder1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureHolder1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerBanner;
    private application.customer.design.PictureHolder pictureHolder1;
    private javax.swing.JButton shopButton;
    // End of variables declaration//GEN-END:variables
}
